// ── COLOR TOKENS ──────────────────────────────────────────────────────────────
export const GOLD = "#C9A84C";
export const GOLD_BRIGHT = "#E8C56A";
export const LAPIS = "#1B2A4A";
export const LAPIS_DEEP = "#0F1A30";
export const PARCHMENT = "#F2E8D0";
export const SIENNA = "#8B3A2A";

export const BIBLE_VERSION = { es: "NBLA", en: "ESV", pt: "ARC" };

// ── 66 BOOKS REGISTRY ─────────────────────────────────────────────────────────
export const BOOKS = [
  { id: 1, es: "Génesis", en: "Genesis", ab: "Gn", div: "pentateuco", ready: true },
  { id: 2, es: "Éxodo", en: "Exodus", ab: "Éx", div: "pentateuco" },
  { id: 3, es: "Levítico", en: "Leviticus", ab: "Lv", div: "pentateuco" },
  { id: 4, es: "Números", en: "Numbers", ab: "Nm", div: "pentateuco" },
  { id: 5, es: "Deuteronomio", en: "Deuteronomy", ab: "Dt", div: "pentateuco" },
  { id: 6, es: "Josué", en: "Joshua", ab: "Jos", div: "historico-at" },
  { id: 7, es: "Jueces", en: "Judges", ab: "Jue", div: "historico-at" },
  { id: 8, es: "Rut", en: "Ruth", ab: "Rt", div: "historico-at" },
  { id: 9, es: "1 Samuel", en: "1 Samuel", ab: "1S", div: "historico-at" },
  { id: 10, es: "2 Samuel", en: "2 Samuel", ab: "2S", div: "historico-at" },
  { id: 11, es: "1 Reyes", en: "1 Kings", ab: "1R", div: "historico-at" },
  { id: 12, es: "2 Reyes", en: "2 Kings", ab: "2R", div: "historico-at" },
  { id: 13, es: "1 Crónicas", en: "1 Chronicles", ab: "1Cr", div: "historico-at" },
  { id: 14, es: "2 Crónicas", en: "2 Chronicles", ab: "2Cr", div: "historico-at" },
  { id: 15, es: "Esdras", en: "Ezra", ab: "Esd", div: "historico-at" },
  { id: 16, es: "Nehemías", en: "Nehemiah", ab: "Neh", div: "historico-at" },
  { id: 17, es: "Ester", en: "Esther", ab: "Est", div: "historico-at" },
  { id: 18, es: "Job", en: "Job", ab: "Job", div: "sabiduria" },
  { id: 19, es: "Salmos", en: "Psalms", ab: "Sal", div: "sabiduria" },
  { id: 20, es: "Proverbios", en: "Proverbs", ab: "Pr", div: "sabiduria" },
  { id: 21, es: "Eclesiastés", en: "Ecclesiastes", ab: "Ecl", div: "sabiduria" },
  { id: 22, es: "Cantares", en: "Song of Solomon", ab: "Cnt", div: "sabiduria" },
  { id: 23, es: "Isaías", en: "Isaiah", ab: "Is", div: "profetas-mayores" },
  { id: 24, es: "Jeremías", en: "Jeremiah", ab: "Jer", div: "profetas-mayores" },
  { id: 25, es: "Lamentaciones", en: "Lamentations", ab: "Lm", div: "profetas-mayores" },
  { id: 26, es: "Ezequiel", en: "Ezekiel", ab: "Ez", div: "profetas-mayores" },
  { id: 27, es: "Daniel", en: "Daniel", ab: "Dn", div: "profetas-mayores" },
  { id: 28, es: "Oseas", en: "Hosea", ab: "Os", div: "profetas-menores" },
  { id: 29, es: "Joel", en: "Joel", ab: "Jl", div: "profetas-menores" },
  { id: 30, es: "Amós", en: "Amos", ab: "Am", div: "profetas-menores" },
  { id: 31, es: "Abdías", en: "Obadiah", ab: "Abd", div: "profetas-menores" },
  { id: 32, es: "Jonás", en: "Jonah", ab: "Jon", div: "profetas-menores" },
  { id: 33, es: "Miqueas", en: "Micah", ab: "Miq", div: "profetas-menores" },
  { id: 34, es: "Nahúm", en: "Nahum", ab: "Nah", div: "profetas-menores" },
  { id: 35, es: "Habacuc", en: "Habakkuk", ab: "Hab", div: "profetas-menores" },
  { id: 36, es: "Sofonías", en: "Zephaniah", ab: "Sof", div: "profetas-menores" },
  { id: 37, es: "Hageo", en: "Haggai", ab: "Hag", div: "profetas-menores" },
  { id: 38, es: "Zacarías", en: "Zechariah", ab: "Zac", div: "profetas-menores" },
  { id: 39, es: "Malaquías", en: "Malachi", ab: "Mal", div: "profetas-menores" },
  { id: 40, es: "Mateo", en: "Matthew", ab: "Mt", div: "evangelios" },
  { id: 41, es: "Marcos", en: "Mark", ab: "Mr", div: "evangelios" },
  { id: 42, es: "Lucas", en: "Luke", ab: "Lc", div: "evangelios" },
  { id: 43, es: "Juan", en: "John", ab: "Jn", div: "evangelios" },
  { id: 44, es: "Hechos", en: "Acts", ab: "Hch", div: "historia-nt" },
  { id: 45, es: "Romanos", en: "Romans", ab: "Ro", div: "paulinas" },
  { id: 46, es: "1 Corintios", en: "1 Corinthians", ab: "1Co", div: "paulinas" },
  { id: 47, es: "2 Corintios", en: "2 Corinthians", ab: "2Co", div: "paulinas" },
  { id: 48, es: "Gálatas", en: "Galatians", ab: "Gá", div: "paulinas" },
  { id: 49, es: "Efesios", en: "Ephesians", ab: "Ef", div: "paulinas" },
  { id: 50, es: "Filipenses", en: "Philippians", ab: "Fil", div: "paulinas" },
  { id: 51, es: "Colosenses", en: "Colossians", ab: "Col", div: "paulinas" },
  { id: 52, es: "1 Tesalonicenses", en: "1 Thessalonians", ab: "1Ts", div: "paulinas" },
  { id: 53, es: "2 Tesalonicenses", en: "2 Thessalonians", ab: "2Ts", div: "paulinas" },
  { id: 54, es: "1 Timoteo", en: "1 Timothy", ab: "1Ti", div: "paulinas" },
  { id: 55, es: "2 Timoteo", en: "2 Timothy", ab: "2Ti", div: "paulinas" },
  { id: 56, es: "Tito", en: "Titus", ab: "Tit", div: "paulinas" },
  { id: 57, es: "Filemón", en: "Philemon", ab: "Flm", div: "paulinas" },
  { id: 58, es: "Hebreos", en: "Hebrews", ab: "He", div: "generales" },
  { id: 59, es: "Santiago", en: "James", ab: "Stg", div: "generales" },
  { id: 60, es: "1 Pedro", en: "1 Peter", ab: "1P", div: "generales" },
  { id: 61, es: "2 Pedro", en: "2 Peter", ab: "2P", div: "generales" },
  { id: 62, es: "1 Juan", en: "1 John", ab: "1Jn", div: "generales" },
  { id: 63, es: "2 Juan", en: "2 John", ab: "2Jn", div: "generales" },
  { id: 64, es: "3 Juan", en: "3 John", ab: "3Jn", div: "generales" },
  { id: 65, es: "Judas", en: "Jude", ab: "Jud", div: "generales" },
  { id: 66, es: "Apocalipsis", en: "Revelation", ab: "Ap", div: "profecia" },
];

// ── DIVISIONS ─────────────────────────────────────────────────────────────────
export const DIVISIONS = [
  {
    id: "pentateuco", titulo: "Pentateuco", tituloEn: "The Pentateuch", tituloPt: "O Pentateuco",
    color: "#88C088", rango: "Génesis – Deuteronomio", testamento: "Antiguo",
    tagline: "La Torá — el fundamento de toda revelación posterior",
    resumen: "Los cinco primeros libros del canon, atribuidos por la tradición reformada a la autoría mosaica (con la posible excepción del relato de su muerte en Dt 34, añadido por una mano posterior, probablemente Josué). Narran desde la creación del cosmos hasta la muerte de Moisés a las puertas de Canaán: la cosmogonía, la caída, el diluvio, el llamado patriarcal, el éxodo, la entrega de la Ley en Sinaí y la peregrinación por el desierto.",
    fondoHistorico: "Compuesto en el contexto del Bronce Tardío (c. 1446–1406 a.C. según la cronología larga reformada, que toma 1R 6:1 como dato literal), el Pentateuco refleja con precisión el mundo del Antiguo Oriente Próximo del segundo milenio: tratados de vasallaje hititas (la estructura del pacto en Éxodo y Deuteronomio sigue el formato de tratado suzerano-vasallo del s. XIV–XIII a.C.), prácticas legales mesopotámicas (paralelos y contrastes con el Código de Hammurabi), y la cultura egipcia del Imperio Nuevo que domina el trasfondo de Éxodo. La crítica documentaria (JEDP, Wellhausen) propuso una composición tardía y compuesta; la posición reformada confiesa la autoría mosaica sustancial, consistente con el testimonio de Cristo mismo (Jn 5:46; Lc 24:27,44) y de los apóstoles.",
    porQueAgrupados: "Estos cinco libros forman una sola obra literaria continua — la Torá — unida por la genealogía narrativa (toledot), por la autoría mosaica y, sobre todo, porque juntos establecen el marco teológico que todo el resto de la Escritura presupone: la doctrina de Dios como Creador, la naturaleza del pecado, la elección de un pueblo pactual, y la Ley como expresión del carácter divino. Ningún libro posterior del canon puede leerse correctamente sin el Pentateuco como cimiento.",
    epocaPacto: "Aquí se establecen, en sucesión, el Pacto Adámico (obras), el Pacto Noáico (preservación universal) y el Pacto Abrahánico (promesa de tierra, simiente y bendición) — y al cierre del Pentateuco, el Pacto Mosaico (Ley) administra ese mismo pacto de gracia bajo la nación de Israel como pueblo de posesión exclusiva de Dios.",
    enfoqueCristologico: "El Pentateuco anticipa a Cristo de manera explícita (la simiente de la mujer, Gn 3:15; el profeta semejante a Moisés, Dt 18:15) y típica: el cordero pascual, el sumo sacerdote, el tabernáculo como morada de Dios entre los hombres, y Moisés mismo como mediador y libertador que prefigura al Mediador definitivo.",
    distintivaReformada: "La tradición reformada sostiene la unidad mosaica del Pentateuco frente a la hipótesis documentaria, no por mero conservadurismo sino porque el testimonio interno del propio texto (Ex 24:4; Dt 31:9,24) y el testimonio de Cristo (Jn 5:46–47: 'si creyeseis a Moisés, me creeríais a mí') hacen de la autoría mosaica un asunto de fidelidad a la autoridad de la Escritura misma, no solo de crítica literaria.",
    versiculoClave: "Dt 6:4-5",
    libros: [
      { es: "Génesis", razon: "Los orígenes: creación, caída, diluvio, y el llamado de los patriarcas. Establece cada doctrina fundacional que el resto del canon desarrollará." },
      { es: "Éxodo", razon: "La redención de Israel de la esclavitud egipcia y la entrega de la Ley en Sinaí — el patrón redentor (liberación + pacto) que estructura toda la soteriología bíblica." },
      { es: "Levítico", razon: "El código de santidad y el sistema sacrificial que regula cómo un pueblo pecador puede acercarse a un Dios santo — la base typológica de la obra expiatoria de Cristo." },
      { es: "Números", razon: "El censo y la peregrinación de cuarenta años por el desierto: el juicio sobre la incredulidad de una generación y la fidelidad de Dios para preservar a la siguiente." },
      { es: "Deuteronomio", razon: "El segundo discurso de la Ley, renovación del pacto en la frontera de Canaán — estructurado como un tratado de vasallaje del ANE, cierra el Pentateuco con la muerte de Moisés." },
    ],
  },
  {
    id: "historico-at", titulo: "Histórico", tituloEn: "Historical Books",
    color: "#6AAECF", rango: "Josué – Ester", testamento: "Antiguo",
    tagline: "La conquista, la monarquía y el exilio del pueblo del pacto",
    resumen: "Doce libros que narran la historia de Israel desde la conquista de Canaán bajo Josué (c. 1406 a.C.) hasta la restauración postexílica bajo Esdras y Nehemías (s. V a.C.) — unos novecientos años de historia nacional, abarcando la conquista, el período de los jueces, el establecimiento de la monarquía unida (Saúl, David, Salomón), la división del reino, la apostasía progresiva, el exilio asirio del norte y babilónico del sur, y el retorno bajo el decreto persa de Ciro.",
    fondoHistorico: "Este período se cruza directamente con los grandes imperios documentados extrabíblicamente: la Estela de Merneptah (c. 1208 a.C.) es la primera mención extrabíblica de 'Israel' como entidad en Canaán; la Estela de Tel Dan (s. IX a.C.) menciona la 'casa de David'; los anales asirios de Salmanasar III registran a Acab de Israel en la batalla de Qarqar (853 a.C.); el Cilindro de Ciro (539 a.C.) confirma la política persa de repatriación de pueblos cautivos que permitió el retorno judío descrito en Esdras.",
    porQueAgrupados: "Estos libros comparten género narrativo-historiográfico y trazan una sola línea cronológica continua de la historia nacional de Israel — aunque 1–2 Crónicas relee la misma historia de Samuel-Reyes con un énfasis sacerdotal y davídico distinto, escrito para la comunidad postexílica. Juntos documentan el ciclo pactual repetido: bendición por obediencia, apostasía, juicio, y la fidelidad persistente de Dios a su promesa davídica pese al fracaso humano constante.",
    epocaPacto: "Domina el Pacto Mosaico en su fase de administración nacional (bendiciones y maldiciones de Dt 28 cumpliéndose literalmente), y emerge aquí el Pacto Davídico (2S 7) — la promesa de un trono eterno que ningún rey humano de esta división cumple plenamente, dejando una tensión que solo Cristo resuelve.",
    enfoqueCristologico: "El fracaso sostenido de cada rey humano —incluso David y Salomón— para encarnar plenamente la justicia del reino de Dios genera una expectativa mesiánica creciente. El trono davídico vacío tras el exilio (no hay rey en Esdras-Nehemías) deja al lector del canon esperando al Hijo de David prometido (2S 7:12-13) cuyo reino sí será eterno.",
    distintivaReformada: "La tradición reformada lee estos libros no como mera crónica política sino como historiografía teológica: cada evento se narra para mostrar la fidelidad del pacto de Dios pese a la infidelidad humana — un patrón que culmina, no en la institución monárquica israelita, sino en el Rey perfecto que esa institución solo podía prefigurar.",
    versiculoClave: "2S 7:16",
    libros: [
      { es: "Josué", razon: "La conquista de Canaán: cumplimiento de la promesa de la tierra hecha a Abraham, bajo el sucesor de Moisés cuyo nombre (Yehoshua) es la forma hebrea de 'Jesús'." },
      { es: "Jueces", razon: "El ciclo de apostasía-opresión-clamor-liberación bajo jueces carismáticos, documentando la anarquía espiritual de 'cada uno hacía lo que bien le parecía' sin un rey fiel." },
      { es: "Rut", razon: "Una historia de lealtad pactual (hesed) ambientada en el período de los jueces, que culmina en la genealogía davídica — y por tanto mesiánica." },
      { es: "1 Samuel", razon: "La transición de jueces a monarquía: el rechazo del liderazgo carismático, la unción de Saúl y su fracaso, y el ascenso de David." },
      { es: "2 Samuel", razon: "El reinado de David y el Pacto Davídico (2S 7) — la promesa de una dinastía y un trono eternos, eje mesiánico de toda la historia subsiguiente." },
      { es: "1 Reyes", razon: "El apogeo de Salomón y la construcción del templo, seguidos por la división del reino tras su apostasía — el inicio de la decadencia dual." },
      { es: "2 Reyes", razon: "La caída de ambos reinos: Israel al exilio asirio (722 a.C.) y Judá al exilio babilónico (586 a.C.) — el juicio pactual cumplido en la historia." },
      { es: "1 Crónicas", razon: "Relectura sacerdotal-davídica de la historia para la comunidad postexílica, con genealogías que conectan a Adán con David — reafirmando la promesa pese al exilio." },
      { es: "2 Crónicas", razon: "Historia del reino del sur con énfasis en el templo y la reforma religiosa, cerrando con el decreto de Ciro que abre la puerta al retorno." },
      { es: "Esdras", razon: "El retorno del exilio y la reconstrucción del templo bajo el decreto persa — la fidelidad de Dios para restaurar a un remanente." },
      { es: "Nehemías", razon: "La reconstrucción de los muros de Jerusalén y la renovación del pacto bajo Esdras y Nehemías, estableciendo la comunidad postexílica." },
      { es: "Ester", razon: "La preservación providencial del pueblo judío en la diáspora persa — Dios actúa sin ser mencionado explícitamente, modelo de providencia oculta." },
    ],
  },
  {
    id: "sabiduria", titulo: "Sabiduría y Poesía", tituloEn: "Wisdom & Poetry",
    color: "#C49AE0", rango: "Job – Cantares", testamento: "Antiguo",
    tagline: "La piedad reflexiva: sufrimiento, adoración, sabiduría práctica y amor pactual",
    resumen: "Cinco libros de género poético hebreo (caracterizado por el paralelismo de pensamiento, no la rima) que tratan, cada uno desde un ángulo distinto, la pregunta de cómo vivir sabiamente delante de Dios: el sufrimiento del justo (Job), la adoración congregacional e individual (Salmos), la sabiduría práctica cotidiana (Proverbios), el sinsentido aparente de la vida 'bajo el sol' (Eclesiastés), y el amor conyugal como don bueno de Dios (Cantares).",
    fondoHistorico: "La literatura sapiencial era un género panorámico del Antiguo Oriente Próximo —existen paralelos egipcios (la Instrucción de Amenemope, con semejanzas notables a Pr 22:17–24:22) y mesopotámicos (el 'Job babilónico', Ludlul Bel Nemeqi)— pero la sabiduría bíblica se distingue radicalmente al fundamentar toda sabiduría en 'el temor de Jehová' (Pr 1:7; 9:10) y no en la mera observación pragmática del orden cósmico.",
    porQueAgrupados: "Comparten forma poética hebrea y función reflexiva: a diferencia de los libros históricos (que narran lo que Dios hizo) o proféticos (que declaran lo que Dios dice que hará), estos libros exploran cómo el pueblo del pacto debe pensar, sentir, sufrir, adorar y amar delante de Dios en medio de la vida ordinaria y extraordinaria.",
    epocaPacto: "Estos libros no avanzan la línea narrativa del pacto sino que la presuponen, dándole expresión emocional y reflexiva: los Salmos son la voz orante de Israel bajo el pacto davídico; Proverbios aplica la sabiduría de la Ley a la vida diaria; Job antecede formalmente a Sinaí pero confronta la pregunta universal de la justicia divina.",
    enfoqueCristologico: "Los Salmos son citados en el NT más que cualquier otro libro del AT como referidos directamente a Cristo (el Salmo 22 en la cruz, el Salmo 110 como el más citado de todo el NT). Job anticipa la necesidad de un mediador-árbitro entre Dios y el hombre (Job 9:33; 19:25, 'yo sé que mi Redentor vive'). Proverbios personifica la Sabiduría (Pr 8) de un modo que el NT aplica a Cristo, la sabiduría de Dios encarnada (1Co 1:24).",
    distintivaReformada: "La tradición reformada lee los Salmos como el manual de oración inspirado de la iglesia —Calvino los llamó 'una anatomía de todas las partes del alma'— y sostiene que Eclesiastés no enseña escepticismo sino que demuestra, mediante la experiencia de Salomón, la futilidad de buscar sentido último 'bajo el sol' aparte de Dios, preparando al lector para la trascendencia que solo la revelación divina provee.",
    versiculoClave: "Pr 1:7",
    libros: [
      { es: "Job", razon: "La pregunta del sufrimiento inocente confrontada sin respuestas fáciles, resuelta no con explicación sino con la revelación de la soberanía y sabiduría incomprensibles de Dios (Job 38-41)." },
      { es: "Salmos", razon: "150 oraciones y cánticos que expresan toda la gama de la experiencia humana delante de Dios — lamento, alabanza, confianza, arrepentimiento — el himnario inspirado de la fe del pacto." },
      { es: "Proverbios", razon: "Sabiduría práctica para la vida cotidiana, fundamentada en 'el temor de Jehová' como principio de todo conocimiento verdadero (Pr 1:7)." },
      { es: "Eclesiastés", razon: "La búsqueda de sentido 'bajo el sol' que termina en vanidad aparte de Dios, concluyendo que el deber del hombre es temer a Dios y guardar sus mandamientos (Ec 12:13)." },
      { es: "Cantares", razon: "Un poema de amor conyugal que celebra el matrimonio como don bueno de Dios, leído tradicionalmente también como figura del amor de Cristo por su Iglesia." },
    ],
  },
  {
    id: "profetas-mayores", titulo: "Profetas Mayores", tituloEn: "Major Prophets",
    color: "#E08870", rango: "Isaías – Daniel", testamento: "Antiguo",
    tagline: "Voces extensas de juicio y esperanza en el ocaso de las dos monarquías",
    resumen: "Cinco libros llamados 'mayores' no por mayor importancia espiritual sino por su extensión literaria. Isaías, Jeremías (junto con Lamentaciones, su elegía sobre la caída de Jerusalén), Ezequiel y Daniel ministran durante el período más oscuro de la historia de Israel: el ocaso del reino del sur, la caída de Jerusalén (586 a.C.) y el exilio babilónico — combinando denuncia del pecado del pacto, anuncio de juicio inminente, y promesas de restauración futura centradas en un Mesías venidero.",
    fondoHistorico: "Este período (c. 740–530 a.C.) coincide con el ascenso y caída del imperio neo-asirio y el ascenso del imperio neo-babilónico bajo Nabucodonosor II, documentado extensamente en las Crónicas Babilónicas y los anales asirios.",
    porQueAgrupados: "Comparten extensión, género oracular-narrativo mixto, y el contexto histórico compartido del juicio y exilio de Judá — aunque Ezequiel y Daniel profetizan ya desde el exilio mismo en Babilonia, mientras Isaías y Jeremías lo anuncian de antemano desde Jerusalén.",
    epocaPacto: "Estos libros operan bajo la 'Anticipación Profética': el pacto mosaico ha sido roto de manera flagrante (las maldiciones de Dt 28 se cumplen literalmente en el exilio), pero Dios promete, a través de estos mismos profetas, un Nuevo Pacto (Jer 31:31-34) que tendrá éxito donde el pacto mosaico, dada la dureza del corazón humano, no pudo.",
    enfoqueCristologico: "Isaías 53 es el texto del Siervo Sufriente más citado del AT respecto a la expiación sustitutiva de Cristo. Jeremías 31 profetiza explícitamente el Nuevo Pacto que Cristo instituye en la Última Cena (Lc 22:20). Ezequiel anuncia el corazón nuevo y el Espíritu nuevo (Ez 36:26-27) que se cumplen en Pentecostés. Daniel 7 presenta al 'Hijo del Hombre' — el título que Jesús usa más de sí mismo en los evangelios.",
    distintivaReformada: "La hermenéutica reformada lee estas profecías con un cumplimiento ya/todavía-no: el Nuevo Pacto se inaugura en la primera venida de Cristo y se consuma en la segunda, rechazando tanto la lectura dispensacionalista de un cumplimiento exclusivamente futuro-nacional como la lectura crítica que las trata como mera literatura post-eventum.",
    versiculoClave: "Is 53:5",
    libros: [
      { es: "Isaías", razon: "El 'quinto evangelio' del AT — desde el juicio sobre Judá hasta la consolación del Siervo Sufriente (cap. 53) y la nueva creación (caps. 65-66)." },
      { es: "Jeremías", razon: "El 'profeta llorón' que anuncia la inminente caída de Jerusalén y, en medio del juicio, la promesa explícita de un Nuevo Pacto (Jer 31:31-34)." },
      { es: "Lamentaciones", razon: "Cinco poemas elegíacos que lamentan la destrucción de Jerusalén en el 586 a.C., sosteniendo la esperanza en la fidelidad de Dios en medio de la desolación (Lm 3:22-23)." },
      { es: "Ezequiel", razon: "Visiones proféticas desde el exilio babilónico mismo: la gloria de Dios que abandona el templo y promete regresar, y la promesa del corazón nuevo y el Espíritu (Ez 36)." },
      { es: "Daniel", razon: "Narrativas de fidelidad en la corte pagana y visiones apocalípticas de los imperios sucesivos y el reino eterno del 'Hijo del Hombre' (Dn 7)." },
    ],
  },
  {
    id: "profetas-menores", titulo: "Profetas Menores", tituloEn: "Minor Prophets",
    color: "#D4955A", rango: "Oseas – Malaquías", testamento: "Antiguo",
    tagline: "El Libro de los Doce — voces breves abarcando tres siglos de la historia del pacto",
    resumen: "Doce libros breves (de ahí 'menores', por extensión, no por importancia) que en la tradición hebrea se contaban como un solo rollo, 'El Libro de los Doce'. Abarcan desde el s. VIII a.C. (Oseas, Amós, Jonás, Miqueas) hasta el período postexílico (Hageo, Zacarías, Malaquías, s. VI–V a.C.).",
    fondoHistorico: "Amós profetiza durante el apogeo económico y la corrupción social del reinado de Jeroboam II en Israel (c. 760 a.C.), un período de prosperidad documentado arqueológicamente en los marfiles de Samaria que el propio Amós denuncia (Am 6:4). Jonás está ambientado en Nínive bajo el imperio asirio anterior a su caída (la ciudad cayó en 612 a.C., evento que Nahúm profetiza con detalle).",
    porQueAgrupados: "Agrupados desde la antigüedad por su brevedad compartida y porque juntos —más que individualmente— trazan el arco completo del ministerio profético preexílico, exílico y postexílico, formando una sola narrativa profética coherente cuando se leen en conjunto, pese a abarcar siglos y autores distintos.",
    epocaPacto: "Igual que los profetas mayores, ministran bajo la 'Anticipación Profética', pero los Doce añaden un énfasis distintivo: el alcance del juicio y la misericordia de Dios hacia las naciones gentiles (Jonás a Nínive, la profecía de las naciones en Amós 1-2), anticipando la inclusión de los gentiles en el pacto de gracia.",
    enfoqueCristologico: "Miqueas 5:2 profetiza el lugar de nacimiento del Mesías, citado literalmente en Mt 2:6. Zacarías profetiza la entrada triunfal (Zac 9:9, citada en Mt 21:5) y el precio de la traición (Zac 11:12-13, cumplida en Mt 27:9-10). Malaquías anuncia al precursor que prepara el camino (Mal 3:1; 4:5-6), identificado por Jesús mismo con Juan el Bautista (Mt 11:14).",
    distintivaReformada: "La tradición reformada destaca que estos doce profetas, pese a su brevedad individual, sostienen unánimemente la misma teología del pacto que los profetas mayores: el llamado a la justicia social como fruto necesario —no opcional— de la fe genuina (Am 5:24; Miq 6:8).",
    versiculoClave: "Miq 6:8",
    libros: [
      { es: "Oseas", razon: "El matrimonio del profeta con una mujer infiel se convierte en metáfora viva de la infidelidad de Israel y el amor pactual inquebrantable de Dios." },
      { es: "Joel", razon: "Una plaga de langostas se convierte en figura del Día de Jehová venidero, con la promesa del derramamiento del Espíritu (Jl 2:28-32) citada por Pedro en Pentecostés (Hch 2)." },
      { es: "Amós", razon: "Denuncia profética de la injusticia social y la religiosidad vacía en el próspero reino del norte: 'corra el juicio como las aguas' (Am 5:24)." },
      { es: "Abdías", razon: "El libro más breve del AT, un oráculo de juicio contra Edom por su traición fraternal hacia Judá en el día de su calamidad." },
      { es: "Jonás", razon: "Un profeta reticente enviado a Nínive, la capital enemiga, revelando que la misericordia de Dios no se limita a Israel sino que alcanza a las naciones." },
      { es: "Miqueas", razon: "Anuncia tanto el juicio sobre la injusticia social como el nacimiento del Mesías en Belén (Miq 5:2) y la esencia de la piedad genuina (Miq 6:8)." },
      { es: "Nahúm", razon: "Profetiza la caída de Nínive —cumplida en el 612 a.C.— como vindicación de la justicia de Dios tras la conversión temporal de la ciudad en Jonás." },
      { es: "Habacuc", razon: "Un diálogo entre el profeta y Dios sobre el uso de una nación más impía (Babilonia) para juzgar a Judá, resuelto en 'el justo por su fe vivirá' (Hab 2:4), citado tres veces en el NT." },
      { es: "Sofonías", razon: "Anuncia el Día de Jehová como juicio universal y, a la vez, como restauración futura con gozo: 'se gozará sobre ti con cánticos' (Sof 3:17)." },
      { es: "Hageo", razon: "Llama al remanente postexílico a reconstruir el templo, prometiendo que la gloria de esta segunda casa superará a la primera." },
      { es: "Zacarías", razon: "Visiones nocturnas y oráculos mesiánicos que anticipan tanto el primer advenimiento humilde (Zac 9:9) como el reinado final de Jehová sobre toda la tierra." },
      { es: "Malaquías", razon: "El último libro del AT canónico: denuncia la apatía sacerdotal postexílica y anuncia al precursor (Elías) que preparará el camino del Señor." },
    ],
  },
  {
    id: "evangelios", titulo: "Evangelios", tituloEn: "Gospels",
    color: "#C9A84C", rango: "Mateo – Juan", testamento: "Nuevo",
    tagline: "El cumplimiento — la vida, muerte y resurrección de Jesucristo",
    resumen: "Cuatro relatos complementarios, no contradictorios, de la persona y obra de Jesucristo, escritos para audiencias y con énfasis distintos: Mateo presenta a Jesús como el Mesías davídico que cumple la Ley y los profetas, dirigido principalmente a lectores judíos; Marcos lo retrata como el Siervo activo y sufriente en una narrativa ágil; Lucas, escrito por un médico gentil, enfatiza la compasión universal de Cristo hacia los marginados; Juan, el más tardío y teológicamente explícito, presenta a Jesús como el Verbo eterno encarnado.",
    fondoHistorico: "Los tres primeros evangelios (Mateo, Marcos, Lucas) se denominan 'sinópticos' por su estrecha relación literaria compartida —el llamado 'problema sinóptico'— con la posición mayoritaria (incluida la reformada-evangélica) sosteniendo la prioridad de Marcos como fuente más temprana (c. 55-65 d.C.).",
    porQueAgrupados: "Comparten género (bios greco-romano aplicado teológicamente) y sujeto único: la persona de Jesucristo. Forman, junto con Hechos, el centro absoluto del canon — el punto hacia el cual converge todo el Antiguo Testamento y del cual fluye todo el Nuevo.",
    epocaPacto: "Esta es la época del 'Cumplimiento' (Vos): el Reino de Dios anunciado por los profetas irrumpe en la historia en la persona de Cristo. El Nuevo Pacto profetizado por Jeremías 31 se inaugura literalmente en la Última Cena (Mt 26:28; Lc 22:20) y se sella con la muerte y resurrección de Cristo.",
    enfoqueCristologico: "Los evangelios son, por definición, el centro cristológico absoluto del canon: cada palabra y acción de Cristo cumple las Escrituras del AT (la fórmula 'para que se cumpliese' aparece repetidamente en Mateo) y establece el fundamento histórico sobre el cual descansa toda la doctrina apostólica posterior.",
    distintivaReformada: "La tradición reformada insiste en la armonía sustancial —no la identidad verbal mecánica— de los cuatro evangelios como testigos complementarios e inspirados del mismo Cristo histórico, rechazando tanto la armonización forzada que ignora el énfasis teológico distintivo de cada evangelista como la crítica de fuentes que disuelve su fiabilidad histórica.",
    versiculoClave: "Jn 1:14",
    libros: [
      { es: "Mateo", razon: "Escrito para una audiencia judía, demuestra sistemáticamente que Jesús cumple la Ley y los profetas como el Mesías davídico prometido; estructura el Sermón del Monte como la nueva Torá del Reino." },
      { es: "Marcos", razon: "El evangelio más breve y dinámico, centrado en la acción y el sufrimiento de Jesús como el Siervo de Jehová; probablemente la fuente más temprana usada por Mateo y Lucas." },
      { es: "Lucas", razon: "Escrito por un médico gentil con rigor historiográfico (Lc 1:1-4), enfatiza la compasión de Cristo hacia pobres, mujeres, samaritanos y pecadores marginados." },
      { es: "Juan", razon: "El evangelio teológico por excelencia: presenta a Jesús como el Logos eterno encarnado (Jn 1:1,14) mediante siete señales y siete declaraciones 'Yo Soy' que revelan su deidad." },
    ],
  },
  {
    id: "historia-nt", titulo: "Historia", tituloEn: "History",
    color: "#56C4AA", rango: "Hechos", testamento: "Nuevo",
    tagline: "El nacimiento y expansión de la iglesia apostólica",
    resumen: "Un solo libro —Hechos de los Apóstoles, segundo volumen de la obra de Lucas— que narra la expansión del evangelio desde Jerusalén hasta Roma a través de la obra del Espíritu Santo, desde Pentecostés hasta el encarcelamiento de Pablo en Roma (c. 30-62 d.C.).",
    fondoHistorico: "Hechos demuestra una precisión historiográfica notable, confirmada por la arqueología y la historia secular: los títulos políticos exactos para cada región (procónsul en Chipre y Acaya, Hch 13:7; 18:12; asiarcas en Éfeso, Hch 19:31) que cambiaban según el estatus administrativo romano de cada provincia, verificados por inscripciones.",
    porQueAgrupados: "Constituye su propia categoría porque no es evangelio (no narra la vida terrenal de Cristo) ni epístola (no es carta doctrinal) sino historiografía eclesial: el puente narrativo indispensable entre el ministerio terrenal de Cristo y las cartas apostólicas que presuponen las iglesias que Hechos describe estar fundándose.",
    epocaPacto: "Sigue dentro del 'Cumplimiento', pero documenta su aplicación expansiva: el derramamiento del Espíritu en Pentecostés (Hch 2) inaugura la era de la iglesia, y el Concilio de Jerusalén (Hch 15) resuelve formalmente que el Nuevo Pacto incluye a los gentiles sin las obras de la Ley mosaica.",
    enfoqueCristologico: "Hechos documenta el Cristo resucitado y ascendido continuando su obra desde el cielo a través de su Espíritu y su iglesia ('todas las cosas que Jesús comenzó a hacer y a enseñar', Hch 1:1, implicando que Hechos narra lo que Jesús continúa haciendo).",
    distintivaReformada: "La tradición reformada lee Hechos como el registro normativo —no necesariamente repetible en cada detalle— de la fundación apostólica de la iglesia, distinguiendo entre lo descriptivo (lo que ocurrió una vez en la era apostólica fundacional) y lo prescriptivo (lo que la iglesia debe practicar permanentemente).",
    versiculoClave: "Hch 1:8",
    libros: [
      { es: "Hechos", razon: "Único libro de su categoría: documenta el nacimiento de la iglesia en Pentecostés y su expansión geográfica y étnica desde Jerusalén hasta Roma, estableciendo el puente histórico entre los evangelios y las epístolas." },
    ],
  },
  {
    id: "paulinas", titulo: "Epístolas Paulinas", tituloEn: "Pauline Epistles",
    color: "#90D060", rango: "Romanos – Filemón", testamento: "Nuevo",
    tagline: "La doctrina apostólica aplicada a iglesias y personas concretas",
    resumen: "Trece cartas atribuidas al apóstol Pablo, escritas a iglesias específicas (Romanos a Filemón) y a colaboradores individuales (las Pastorales: 1-2 Timoteo, Tito), abarcando desde la exposición doctrinal más sistemática del NT (Romanos) hasta una breve carta personal sobre un esclavo fugitivo (Filemón).",
    fondoHistorico: "Las cartas paulinas se escribieron en el contexto de los tres viajes misioneros de Pablo y su posterior encarcelamiento romano (c. 48-67 d.C.), documentado en Hechos.",
    porQueAgrupados: "Comparten autoría paulina y género epistolar (carta ocasional greco-romana adaptada a propósito doctrinal y pastoral), tradicionalmente ordenadas por extensión decreciente más que por orden cronológico de composición.",
    epocaPacto: "Época de 'Aplicación': estas cartas no narran eventos redentores nuevos sino que aplican el evangelio ya cumplido en Cristo —su muerte, resurrección y señorío— a la doctrina, la ética y la vida eclesial de comunidades concretas.",
    enfoqueCristologico: "Pablo desarrolla con mayor profundidad sistemática que cualquier otro autor del NT la doctrina de la justificación por fe en la obra de Cristo (Romanos, Gálatas), la unión del creyente con Cristo, y la supremacía cósmica de Cristo sobre toda la creación (Col 1:15-20).",
    distintivaReformada: "Romanos y Gálatas son, junto con los evangelios, el fundamento textual primario de la doctrina reformada de la justificación por fe sola (sola fide) frente a toda forma de justificación por obras.",
    versiculoClave: "Ro 1:16-17",
    libros: [
      { es: "Romanos", razon: "La exposición sistemática más completa del evangelio en el NT: pecado universal, justificación por fe, santificación, la soberanía electiva de Dios, y la ética cristiana — el tratado doctrinal por excelencia de Pablo." },
      { es: "1 Corintios", razon: "Corrección pastoral de divisiones, inmoralidad, desorden litúrgico y confusión doctrinal en una iglesia gentil problemática, culminando en la defensa clásica de la resurrección (cap. 15)." },
      { es: "2 Corintios", razon: "La carta más personal de Pablo, defendiendo su apostolado legítimo frente a falsos apóstoles y exponiendo la teología del sufrimiento y la suficiencia de la gracia." },
      { es: "Gálatas", razon: "El manifiesto de la justificación por fe sola frente a los judaizantes que exigían la circuncisión: 'el evangelio de la libertad' frente a todo legalismo." },
      { es: "Efesios", razon: "La eclesiología cósmica de Pablo: la iglesia como el cuerpo de Cristo, unidad de judíos y gentiles, y la armadura espiritual para la guerra cristiana." },
      { es: "Filipenses", razon: "Carta de gozo escrita desde prisión, con el himno cristológico de la kénosis (Fil 2:5-11) como uno de los textos cristológicos más densos del NT." },
      { es: "Colosenses", razon: "Defensa de la supremacía absoluta de Cristo frente a un sincretismo filosófico-religioso temprano que amenazaba con relativizar su persona y obra." },
      { es: "1 Tesalonicenses", razon: "Una de las cartas más tempranas de Pablo, con enseñanza pastoral sobre la santificación y la esperanza escatológica del regreso de Cristo." },
      { es: "2 Tesalonicenses", razon: "Corrección de una confusión escatológica sobre el 'día del Señor', con la revelación del 'hombre de pecado' que debe preceder la segunda venida." },
      { es: "1 Timoteo", razon: "Carta pastoral con instrucciones sobre el orden eclesial, la cualificación de ancianos y diáconos, y la defensa de la sana doctrina frente a falsos maestros." },
      { es: "2 Timoteo", razon: "El testamento final de Pablo, escrito en prisión poco antes de su martirio, exhortando a Timoteo a la fidelidad doctrinal y al sufrimiento por el evangelio." },
      { es: "Tito", razon: "Instrucciones para organizar el liderazgo de la iglesia en Creta y para que la sana doctrina produzca buenas obras visibles en cada grupo social." },
      { es: "Filemón", razon: "La carta más breve de Pablo, una apelación personal en favor de Onésimo, un esclavo fugitivo convertido — el evangelio aplicado a una relación social concreta." },
    ],
  },
  {
    id: "generales", titulo: "Epístolas Generales", tituloEn: "General Epistles",
    color: "#D06898", rango: "Hebreos – Judas", testamento: "Nuevo",
    tagline: "Voces apostólicas complementarias para una iglesia dispersa y perseguida",
    resumen: "Ocho cartas de autoría no paulina —Hebreos (autor anónimo en el texto mismo), Santiago, 1-2 Pedro, 1-3 Juan y Judas— dirigidas, en su mayoría, a audiencias más amplias y dispersas que las cartas paulinas, enfrentando la persecución, la persistencia de falsa doctrina y la necesidad de perseverancia en la fe.",
    fondoHistorico: "Hebreos se dirige a cristianos de trasfondo judío tentados a retroceder al judaísmo bajo presión de persecución, probablemente antes de la destrucción del templo en el 70 d.C. Santiago, posiblemente la carta más temprana del NT (c. 45-48 d.C.), refleja un judaísmo cristiano primitivo previo al Concilio de Jerusalén.",
    porQueAgrupados: "Agrupadas por exclusión (no son paulinas) y por destinatarios más generales que congregaciones específicas, estas cartas aportan perspectivas apostólicas complementarias —sacerdotal (Hebreos), práctica (Santiago), pastoral-sufriente (1-2 Pedro), relacional (1-3 Juan) y polémica (Judas).",
    epocaPacto: "También época de 'Aplicación', con un acento distintivo en la perseverancia bajo sufrimiento y la advertencia contra la apostasía y la falsa doctrina que amenazaban a las comunidades cristianas dispersas del primer siglo.",
    enfoqueCristologico: "Hebreos presenta la cristología sacerdotal más desarrollada del NT: Cristo como sumo sacerdote según el orden de Melquisedec, superior a los ángeles, a Moisés y al sacerdocio levítico, cuyo sacrificio único y definitivo cumple y abroga el sistema sacrificial completo del AT.",
    distintivaReformada: "La tradición reformada ha debatido históricamente la relación entre Santiago ('la fe sin obras es muerta', Stg 2:26) y Pablo ('por gracia sois salvos... no por obras', Ef 2:8-9), resolviendo —siguiendo a Calvino— que ambos enseñan la misma doctrina desde ángulos distintos.",
    versiculoClave: "He 1:3",
    libros: [
      { es: "Hebreos", razon: "Demuestra la superioridad de Cristo sobre ángeles, Moisés y el sacerdocio levítico, con la exhortación central a perseverar en la fe frente a la tentación de retroceder al judaísmo." },
      { es: "Santiago", razon: "Sabiduría práctica intensamente ética, insistiendo en que la fe genuina se demuestra necesariamente en obras visibles — complemento, no contradicción, de la doctrina paulina de la justificación." },
      { es: "1 Pedro", razon: "Aliento pastoral a cristianos sufriendo persecución y dispersión, llamándolos a la santidad y la esperanza viva fundamentada en la resurrección de Cristo." },
      { es: "2 Pedro", razon: "Advertencia contra falsos maestros y el escepticismo respecto a la segunda venida, con un testamento final del apóstol antes de su martirio." },
      { es: "1 Juan", razon: "Pruebas de la vida eterna genuina —fe correcta, obediencia y amor fraternal— escrita contra un proto-gnosticismo que negaba la encarnación real de Cristo." },
      { es: "2 Juan", razon: "Una breve carta de advertencia contra recibir a falsos maestros que niegan que Cristo vino en carne." },
      { es: "3 Juan", razon: "Una carta personal que elogia la hospitalidad cristiana hacia maestros itinerantes y denuncia el orgullo eclesiástico de Diótrefes." },
      { es: "Judas", razon: "Una polémica urgente contra falsos maestros libertinos infiltrados en la iglesia, citando tradición judía extracanónica para ilustrar el juicio cierto sobre la apostasía." },
    ],
  },
  {
    id: "profecia", titulo: "Profecía", tituloEn: "Prophecy",
    color: "#CC3848", rango: "Apocalipsis", testamento: "Nuevo",
    tagline: "La consumación — el triunfo final de Cristo y la nueva creación",
    resumen: "El libro final del canon, escrito por el apóstol Juan en exilio en la isla de Patmos, combinando los géneros de epístola, profecía y apocalíptica judía para revelar el triunfo escatológico de Cristo sobre todo poder hostil y la consumación final de la historia redentora en la nueva creación.",
    fondoHistorico: "Compuesto durante el reinado de Domiciano (c. 95 d.C., posición mayoritaria reformada, apoyada en el testimonio de Ireneo, discípulo de Policarpo quien conoció al propio Juan) o posiblemente bajo Nerón (c. 68 d.C., minoritaria).",
    porQueAgrupados: "Constituye su propia categoría por ser el único libro plenamente apocalíptico del NT y por su posición canónica deliberada como clímax final de toda la revelación bíblica.",
    epocaPacto: "La época de la 'Consumación': el Reino de Dios, inaugurado en la primera venida de Cristo, se consuma plenamente.",
    enfoqueCristologico: "Apocalipsis presenta la cristología más exaltada y cósmica de todo el canon: Cristo como el Cordero inmolado que es digno de abrir el rollo (cap. 5), el Rey de reyes y Señor de señores que regresa en victoria (cap. 19), y quien hace nuevas todas las cosas (cap. 21).",
    distintivaReformada: "La tradición reformada lee Apocalipsis cristocéntricamente como la consumación gloriosa de la historia redentora completa del canon —no como un mapa cronológico literal de eventos geopolíticos futuros.",
    versiculoClave: "Ap 21:3-4",
    libros: [
      { es: "Apocalipsis", razon: "Cierra el canon con la consumación de toda la historia redentora: el juicio final de todo poder hostil a Dios y la restauración de la nueva creación, donde 'el tabernáculo de Dios está con los hombres' (Ap 21:3)." },
    ],
  },
];

export const DIV_BY_ID = Object.fromEntries(DIVISIONS.map(d => [d.id, d]));

// ── CHAPTER ERAS (Genesis default) ────────────────────────────────────────────
export const CHAPTER_ERAS = [
  { from: 1,  to: 11, color: "#4A6741", label: "CREACIÓN Y CAÍDA · Gn 1–11" },
  { from: 12, to: 25, color: "#1B5E8B", label: "PACTO ABRAHÁNICO · Gn 12–25" },
  { from: 26, to: 36, color: "#6B4A8B", label: "PATRIARCAS · Gn 26–36" },
  { from: 37, to: 50, color: "#1B6B5E", label: "PROVIDENCIA · JOSÉ · Gn 37–50" },
];

// ── TABS ──────────────────────────────────────────────────────────────────────
export const TABS = [
  { id: "overview",  label: "VISIÓN GENERAL" },
  { id: "theology",  label: "TEOLOGÍA" },
  { id: "purpose",   label: "PROPÓSITO" },
  { id: "canon",     label: "CONTEXTO CANÓNICO" },
  { id: "history",   label: "CONTEXTO HISTÓRICO" },
  { id: "verses",    label: "VERSÍCULOS CLAVE" },
  { id: "sources",   label: "FUENTES" },
];

// ── UI TRANSLATIONS ───────────────────────────────────────────────────────────
export const UI = {
  es: {
    appTitle: "Exploración Bíblica Panorámica Interactiva",
    share: "COMPARTIR", copied: "✓ COPIADO",
    ot: "A.T.", nt: "N.T.",
    books: n => `${n} ${n === 1 ? "libro" : "libros"}`,
    cardBooks: n => `${n} ${n === 1 ? "libro" : "libros"} →`,
    tabs: ["VISIÓN GENERAL","TEOLOGÍA","PROPÓSITO","CONTEXTO CANÓNICO","CONTEXTO HISTÓRICO","VERSÍCULOS CLAVE","FUENTES"],
    backToShelf: "← VOLVER AL ESTANTE",
    backToCanon: "← El Canon",
    eyebrow: "Protestantismo Reformado · NBLA · ESV · ARC",
    subline: "Bereshit — En el principio creó Dios los cielos y la tierra",
    metaLabels: ["Título Original","Autor","Fecha de escritura","División Canónica","Idioma Original","Versiones","Escrito en"],
    traditional: "Autoría tradicional",
    canonEntry: n => `#${n} del Canon`,
    hint: "← Arrastra para explorar · Clic en capítulo → BibleGateway NBLA · Clic en personaje → biografía →",
    summariesSteps: [
      "Toca el número del capítulo para leer el pasaje en BibleGateway",
      "Presiona reproducción para escuchar el audio del capítulo",
      "El audio avanza automáticamente al siguiente capítulo al terminar",
      "Toca el ícono de compartir junto al título para copiar el enlace",
    ],
    timelineLabel: "LÍNEA DE PERSONAJES",
    summariesLabel: "AUDIO · CAPÍTULOS",
    pipeline: "CANON PIPELINE v1.2.0 · PROTESTANTISMO REFORMADO · NBLA / ESV / ARC",
    eraLabels: ["CREACIÓN Y CAÍDA · Gn 1–11","PACTO ABRAHÁNICO · Gn 12–25","PATRIARCAS · Gn 26–36","PROVIDENCIA · JOSÉ · Gn 37–50"],
    ot_label: "ANTIGUO TESTAMENTO", nt_label: "NUEVO TESTAMENTO",
    book_s: "LIBRO", book_p: "LIBROS",
    divSections: ["VISIÓN GENERAL","TRASFONDO HISTÓRICO","¿POR QUÉ SE AGRUPAN ASÍ?","CONTEXTO DE PACTO","ENFOQUE CRISTOLÓGICO","DISTINCTIVA REFORMADA","VERSÍCULO CLAVE DE LA DIVISIÓN","LOS LIBROS DE ESTA DIVISIÓN"],
    see: "VER →",
    headerIndex: "Toca una clasificación para conocer su trasfondo histórico, por qué se agrupa así, y los libros que la componen.",
    headerDiv: (t, r) => `Explorando ${t} — ${r}. Toca un libro a la izquierda o derecha, o vuelve al índice de clasificaciones.`,
    headerGenesis: "Recorre la línea de tiempo de Génesis: personajes, capítulos y teología sistemática interactiva.",
    headerBook: b => `Leyendo ${b}. Usa los paneles laterales para saltar a otro libro, o vuelve al estante.`,
    theologyLabels: {
      doctrines: "DOCTRINAS", sysTheology: "TEOLOGÍA SISTEMÁTICA",
      whatTeaches: t => `LO QUE ${t} ENSEÑA`, keyPassages: t => `PASAJES CLAVE EN ${t}`,
      reformed: "DISTINCTIVA REFORMADA", confessions: "CONFESIONES DE FE",
      wcf: "CONFESIÓN DE WESTMINSTER", wcfTeaches: "LO QUE ENSEÑA ESTE CAPÍTULO",
      wcfPassages: t => `PASAJES DE ${t} QUE FUNDAMENTAN ESTE CAPÍTULO`,
      readFull: "LEER CAPÍTULO COMPLETO →",
      wcfHint: t => `Haz clic en una doctrina para ver los versículos de ${t} que fundamentan ese capítulo.`,
    },
    purposeLabels: { historical: "PROPÓSITO HISTÓRICO", theological: "PROPÓSITO TEOLÓGICO", audience: "DESTINATARIO ORIGINAL" },
    canonLabels: {
      position: "POSICIÓN EN LA HISTORIA REDENTORA", genesisMarker: t => `← ${t}`,
      christFocus: "ENFOQUE CRISTOLÓGICO", biblicalTheology: "TEOLOGÍA BÍBLICA (GEERHARDUS VOS)",
      typesShadows: "TIPOS Y SOMBRAS DE CRISTO",
    },
    historyLabels: {
      period: "PERÍODO HISTÓRICO", chronology: "CRONOLOGÍA INTERNA DEL LIBRO",
      geography: "GEOGRAFÍA DEL LIBRO", civilizations: "CIVILIZACIONES EN ESCENA",
      ane: "FUENTES DEL ANTIGUO ORIENTE PRÓXIMO (ANE)", controversies: "CONTROVERSIAS HISTÓRICAS",
      chronologyNote: "Cronología conservadora-reformada (Ussher/masorética). La cronología moderna sitúa estos eventos 1–3 siglos más tarde.",
    },
    sourcesLabels: {
      hint: "Haz clic en cualquier fuente para ver biografía del autor, método y aportación al pipeline",
      viewCard: "Ver ficha completa →", aboutAuthor: "SOBRE EL AUTOR",
      method: "MÉTODO Y ENFOQUE", contribution: "APORTACIÓN AL CANON PIPELINE",
      mainWorks: "OBRAS PRINCIPALES", viewFull: "VER FICHA COMPLETA →",
    },
    characterLabels: {
      actions: "ACCIONES NARRATIVAS", theological: "SIGNIFICADO TEOLÓGICO",
      typeShadow: "TIPO Y SOMBRA DE CRISTO", inNT: "EN EL NUEVO TESTAMENTO",
      keyVerses: "VERSÍCULOS CLAVE",
      bioHint: (a, b, ab) => `${ab} ${a}–${b} · Clic para ver biografía completa`,
    },
    comingSoon: b => `${b} — aún no generado. Este libro se añadirá al pipeline próximamente.`,
    footer: "El Canon · 66 libros · 10 divisiones · tradición reformada",
  },
  en: {
    appTitle: "Interactive Panoramic Bible Exploration",
    share: "SHARE", copied: "✓ COPIED",
    ot: "O.T.", nt: "N.T.",
    books: n => `${n} ${n === 1 ? "book" : "books"}`,
    cardBooks: n => `${n} ${n === 1 ? "book" : "books"} →`,
    tabs: ["OVERVIEW","THEOLOGY","PURPOSE","CANONICAL CONTEXT","HISTORICAL CONTEXT","KEY VERSES","SOURCES"],
    backToShelf: "← BACK TO SHELF",
    backToCanon: "← The Canon",
    eyebrow: "Reformed Protestantism · NBLA · ESV · ARC",
    subline: "Bereshit — In the beginning God created the heavens and the earth",
    metaLabels: ["Original Title","Author","Date Written","Canonical Division","Original Language","Versions","Written In"],
    traditional: "Traditional authorship",
    canonEntry: n => `#${n} of the Canon`,
    hint: "← Drag to explore · Click chapter → BibleGateway ESV · Click character → biography →",
    summariesSteps: [
      "Tap the chapter number to read the passage on BibleGateway",
      "Press play to listen to the chapter audio",
      "Audio automatically advances to the next chapter when done",
      "Tap the share icon next to the title to copy a direct link",
    ],
    timelineLabel: "CHARACTER TIMELINE",
    summariesLabel: "AUDIO · CHAPTERS",
    pipeline: "CANON PIPELINE v1.2.0 · REFORMED PROTESTANTISM · NBLA / ESV / ARC",
    eraLabels: ["CREATION & FALL · Gen 1–11","ABRAHAMIC COVENANT · Gen 12–25","PATRIARCHS · Gen 26–36","PROVIDENCE · JOSEPH · Gen 37–50"],
    ot_label: "OLD TESTAMENT", nt_label: "NEW TESTAMENT",
    book_s: "BOOK", book_p: "BOOKS",
    divSections: ["OVERVIEW","HISTORICAL BACKGROUND","WHY GROUPED TOGETHER?","COVENANT CONTEXT","CHRISTOLOGICAL FOCUS","REFORMED DISTINCTIVE","KEY VERSE OF THE DIVISION","BOOKS IN THIS DIVISION"],
    see: "SEE →",
    headerIndex: "Tap a classification to explore its historical background, why it's grouped this way, and its books.",
    headerDiv: (t, r) => `Exploring ${t} — ${r}. Tap a book on the left or right, or return to the index.`,
    headerGenesis: "Explore the Genesis timeline: characters, chapters, and interactive systematic theology.",
    headerBook: b => `Reading ${b}. Use the side panels to jump to another book, or return to the shelf.`,
    theologyLabels: {
      doctrines: "DOCTRINES", sysTheology: "SYSTEMATIC THEOLOGY",
      whatTeaches: t => `WHAT ${t} TEACHES`, keyPassages: t => `KEY PASSAGES IN ${t}`,
      reformed: "REFORMED DISTINCTIVE", confessions: "CONFESSIONS OF FAITH",
      wcf: "WESTMINSTER CONFESSION", wcfTeaches: "WHAT THIS CHAPTER TEACHES",
      wcfPassages: t => `${t} PASSAGES THAT GROUND THIS CHAPTER`,
      readFull: "READ FULL CHAPTER →",
      wcfHint: t => `Click a doctrine to see the ${t} passages that ground that chapter.`,
    },
    purposeLabels: { historical: "HISTORICAL PURPOSE", theological: "THEOLOGICAL PURPOSE", audience: "ORIGINAL AUDIENCE" },
    canonLabels: {
      position: "POSITION IN REDEMPTIVE HISTORY", genesisMarker: t => `← ${t}`,
      christFocus: "CHRISTOLOGICAL FOCUS", biblicalTheology: "BIBLICAL THEOLOGY (GEERHARDUS VOS)",
      typesShadows: "TYPES AND SHADOWS OF CHRIST",
    },
    historyLabels: {
      period: "HISTORICAL PERIOD", chronology: "INTERNAL CHRONOLOGY OF THE BOOK",
      geography: "BOOK GEOGRAPHY", civilizations: "CIVILIZATIONS IN SCENE",
      ane: "ANCIENT NEAR EAST SOURCES (ANE)", controversies: "HISTORICAL CONTROVERSIES",
      chronologyNote: "Conservative-Reformed chronology (Ussher/Masoretic). Modern scholarship places these events 1–3 centuries later.",
    },
    sourcesLabels: {
      hint: "Click any source to view the author biography, method and contribution to the pipeline",
      viewCard: "View full card →", aboutAuthor: "ABOUT THE AUTHOR",
      method: "METHOD & APPROACH", contribution: "CONTRIBUTION TO CANON PIPELINE",
      mainWorks: "MAIN WORKS", viewFull: "VIEW FULL CARD →",
    },
    characterLabels: {
      actions: "NARRATIVE ACTIONS", theological: "THEOLOGICAL MEANING",
      typeShadow: "TYPE AND SHADOW OF CHRIST", inNT: "IN THE NEW TESTAMENT",
      keyVerses: "KEY VERSES",
      bioHint: (a, b, ab) => `${ab} ${a}–${b} · Click for full biography`,
    },
    comingSoon: b => `${b} — not yet generated. This book will be added to the pipeline soon.`,
    footer: "The Canon · 66 books · 10 divisions · Reformed tradition",
  },
  pt: {
    appTitle: "Exploração Bíblica Panorâmica Interativa",
    share: "COMPARTILHAR", copied: "✓ COPIADO",
    ot: "A.T.", nt: "N.T.",
    books: n => `${n} ${n === 1 ? "livro" : "livros"}`,
    cardBooks: n => `${n} ${n === 1 ? "livro" : "livros"} →`,
    tabs: ["VISÃO GERAL","TEOLOGIA","PROPÓSITO","CONTEXTO CANÔNICO","CONTEXTO HISTÓRICO","VERSÍCULOS-CHAVE","FONTES"],
    backToShelf: "← VOLTAR À ESTANTE",
    backToCanon: "← O Cânon",
    eyebrow: "Protestantismo Reformado · NBLA · ESV · ARC",
    subline: "Bereshit — No princípio Deus criou os céus e a terra",
    metaLabels: ["Título Original","Autor","Data de Composição","Divisão Canônica","Idioma Original","Versões","Escrito em"],
    traditional: "Autoria tradicional",
    canonEntry: n => `#${n} do Cânon`,
    hint: "← Arraste para explorar · Clique no capítulo → BibleGateway ARC · Clique no personagem → biografia →",
    summariesSteps: [
      "Toque o número do capítulo para ler a passagem no BibleGateway",
      "Pressione reprodução para ouvir o áudio do capítulo",
      "O áudio avança automaticamente para o próximo capítulo ao terminar",
      "Toque o ícone de compartilhar ao lado do título para copiar o link",
    ],
    timelineLabel: "LINHA DE PERSONAGENS",
    summariesLabel: "ÁUDIO · CAPÍTULOS",
    pipeline: "CANON PIPELINE v1.2.0 · PROTESTANTISMO REFORMADO · NBLA / ESV / ARC",
    eraLabels: ["CRIAÇÃO E QUEDA · Gn 1–11","ALIANÇA ABRAÂMICA · Gn 12–25","PATRIARCAS · Gn 26–36","PROVIDÊNCIA · JOSÉ · Gn 37–50"],
    ot_label: "ANTIGO TESTAMENTO", nt_label: "NOVO TESTAMENTO",
    book_s: "LIVRO", book_p: "LIVROS",
    divSections: ["VISÃO GERAL","CONTEXTO HISTÓRICO","POR QUE AGRUPADOS ASSIM?","CONTEXTO DE ALIANÇA","ENFOQUE CRISTOLÓGICO","DISTINTIVA REFORMADA","VERSÍCULO-CHAVE DA DIVISÃO","LIVROS DESTA DIVISÃO"],
    see: "VER →",
    headerIndex: "Toque em uma classificação para conhecer seu contexto histórico, por que é agrupada assim e seus livros.",
    headerDiv: (t, r) => `Explorando ${t} — ${r}. Toque em um livro à esquerda ou direita, ou volte ao índice.`,
    headerGenesis: "Explore a linha do tempo de Gênesis: personagens, capítulos e teologia sistemática interativa.",
    headerBook: b => `Lendo ${b}. Use os painéis laterais para ir a outro livro, ou volte à estante.`,
    theologyLabels: {
      doctrines: "DOUTRINAS", sysTheology: "TEOLOGIA SISTEMÁTICA",
      whatTeaches: t => `O QUE ${t} ENSINA`, keyPassages: t => `PASSAGENS-CHAVE EM ${t}`,
      reformed: "DISTINTIVA REFORMADA", confessions: "CONFISSÕES DE FÉ",
      wcf: "CONFISSÃO DE WESTMINSTER", wcfTeaches: "O QUE ESTE CAPÍTULO ENSINA",
      wcfPassages: t => `PASSAGENS DE ${t} QUE FUNDAMENTAM ESTE CAPÍTULO`,
      readFull: "LER CAPÍTULO COMPLETO →",
      wcfHint: t => `Clique em uma doutrina para ver as passagens de ${t} que fundamentam esse capítulo.`,
    },
    purposeLabels: { historical: "PROPÓSITO HISTÓRICO", theological: "PROPÓSITO TEOLÓGICO", audience: "DESTINATÁRIO ORIGINAL" },
    canonLabels: {
      position: "POSIÇÃO NA HISTÓRIA REDENTORA", genesisMarker: t => `← ${t}`,
      christFocus: "ENFOQUE CRISTOLÓGICO", biblicalTheology: "TEOLOGIA BÍBLICA (GEERHARDUS VOS)",
      typesShadows: "TIPOS E SOMBRAS DE CRISTO",
    },
    historyLabels: {
      period: "PERÍODO HISTÓRICO", chronology: "CRONOLOGIA INTERNA DO LIVRO",
      geography: "GEOGRAFIA DO LIVRO", civilizations: "CIVILIZAÇÕES EM CENA",
      ane: "FONTES DO ANTIGO ORIENTE PRÓXIMO (ANE)", controversies: "CONTROVÉRSIAS HISTÓRICAS",
      chronologyNote: "Cronologia conservadora-reformada (Ussher/Massorética). A cronologia moderna situa esses eventos 1–3 séculos mais tarde.",
    },
    sourcesLabels: {
      hint: "Clique em qualquer fonte para ver a biografia do autor, método e contribuição ao pipeline",
      viewCard: "Ver ficha completa →", aboutAuthor: "SOBRE O AUTOR",
      method: "MÉTODO E ABORDAGEM", contribution: "CONTRIBUIÇÃO AO CANON PIPELINE",
      mainWorks: "OBRAS PRINCIPAIS", viewFull: "VER FICHA COMPLETA →",
    },
    characterLabels: {
      actions: "AÇÕES NARRATIVAS", theological: "SIGNIFICADO TEOLÓGICO",
      typeShadow: "TIPO E SOMBRA DE CRISTO", inNT: "NO NOVO TESTAMENTO",
      keyVerses: "VERSÍCULOS-CHAVE",
      bioHint: (a, b, ab) => `${ab} ${a}–${b} · Clique para ver biografia completa`,
    },
    comingSoon: b => `${b} — ainda não gerado. Este livro será adicionado ao pipeline em breve.`,
    footer: "O Cânon · 66 livros · 10 divisões · tradição reformada",
  },
};

// Variable-spaced golden page-line gradient for the tab rail (90deg = vertical lines
// across the rail width). Gaps vary so lines are tighter at the edges and looser in
// the middle, simulating the rounded fore-edge of a closed book.
export const RAIL_BG = (() => {
  const gaps = [2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2];
  const stops = [];
  let x = 0;
  gaps.forEach((g, i) => {
    const col = i % 3 === 0 ? "rgba(201,168,76,0.72)" : "rgba(255,220,80,0.38)";
    stops.push(`transparent ${x}px,${col} ${x}px,${col} ${x + 1}px,transparent ${x + 1}px`);
    x += g + 1;
  });
  return `linear-gradient(90deg,${stops.join(",")})`;
})();

// ── SHELF STYLES (S) ──────────────────────────────────────────────────────────
export const S = {
  outer: { fontFamily: "'Georgia', serif", backgroundColor: "#2C1A0E", backgroundImage: "url('/textures/leather-fine.jpg')", backgroundSize: "300px", backgroundPosition: "center", backgroundAttachment: "fixed", color: PARCHMENT, minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", padding: "28px 16px 48px" },
  topBar: { height: 3, width: "100%", maxWidth: 1400, background: `linear-gradient(90deg, transparent, ${GOLD}, ${SIENNA}, ${GOLD}, transparent)`, flexShrink: 0, marginBottom: 18 },
  appHeader: { width: "100%", maxWidth: 1400, textAlign: "center", marginBottom: 18 },
  appTitle: { fontFamily: "'Georgia',serif", fontSize: "clamp(26px,3.2vw,40px)", fontWeight: 900, color: PARCHMENT, letterSpacing: 0.5, lineHeight: 1.15, marginBottom: 10, textShadow: "0 0 40px rgba(201,168,76,0.25)" },
  headerInstruction: { fontSize: 13.5, fontStyle: "italic", color: "rgba(242,232,208,0.55)", lineHeight: 1.6 },
  bookFrame: { width: "100%", maxWidth: 1400, position: "relative",
    boxShadow: "0 -12px 40px rgba(5,2,0,0.55), 0 -4px 12px rgba(5,2,0,0.60), 0 4px 8px rgba(10,4,0,0.60), 0 14px 40px rgba(10,4,0,0.55), 0 40px 100px rgba(5,2,0,0.45), 0 80px 160px rgba(5,2,0,0.25)",
    borderRadius: 18,
  },
  book: {
    display: "flex", alignItems: "stretch", minHeight: 940,
    backgroundImage: "linear-gradient(180deg, rgba(22,12,5,0.48), rgba(15,8,3,0.54)), url('/textures/leather-fine.jpg')",
    backgroundSize: "auto, 300px", backgroundPosition: "center",
    borderRadius: 18, border: `2px solid rgba(139,94,26,0.55)`,
    boxShadow: "0 40px 100px rgba(0,0,0,0.8), 0 0 0 1px rgba(201,168,76,0.2), inset 0 1px 0 rgba(201,168,76,0.18)",
    overflow: "hidden", position: "relative",
  },
  gutterShadowLeft: { position: "absolute", left: "50%", top: 0, bottom: 0, width: 60, marginLeft: -60, background: "linear-gradient(90deg, transparent, rgba(0,0,0,0.30))", pointerEvents: "none", zIndex: 5 },
  gutterShadowRight: { position: "absolute", left: "50%", top: 0, bottom: 0, width: 60, background: "linear-gradient(90deg, rgba(0,0,0,0.30), transparent)", pointerEvents: "none", zIndex: 5 },
  gutterLine: { position: "absolute", left: "50%", top: 0, bottom: 0, width: 1, background: "rgba(201,168,76,0.18)", zIndex: 6 },
  tabRail: (side) => ({
    width: 84, flexShrink: 0, padding: "12px 2px", position: "relative",
    backgroundImage: `${RAIL_BG}, linear-gradient(180deg, rgba(30,15,3,0.35), rgba(20,10,2,0.45)), url('/textures/pergament.jpg')`, backgroundSize: "auto, auto, cover", backgroundPosition: "center",
    borderRight: side === "left" ? `1px solid rgba(201,168,76,0.15)` : "none",
    borderLeft: side === "right" ? `1px solid rgba(201,168,76,0.15)` : "none",
    overflowY: "auto", overflowX: "hidden",
  }),
  railHeader: { padding: "0 0 8px", marginBottom: 6, borderBottom: `1px solid rgba(201,168,76,0.15)`, textAlign: "center" },
  railTitle: { fontSize: 14, letterSpacing: 3, fontWeight: 700, fontFamily: "'Georgia',serif", color: GOLD },
  railSub: { fontSize: 11, letterSpacing: 1, fontWeight: 500, color: "rgba(242,232,208,0.65)", marginTop: 3 },
  tabColumns: { display: "flex", gap: 0.5 },
  tabColumn: { display: "flex", flexDirection: "column", gap: 5, flex: 1, minWidth: 0 },
  stepTab: (color, active, height, side) => ({
    display: "flex", alignItems: "center", justifyContent: "center",
    width: "100%", marginLeft: 0, minHeight: height, position: "relative",
    cursor: "pointer", padding: "12px 0px",
    backgroundColor: color,
    backgroundImage: active
      ? "linear-gradient(180deg, rgba(0,0,0,0.08), rgba(0,0,0,0.42))"
      : "linear-gradient(180deg, rgba(0,0,0,0.28), rgba(0,0,0,0.60))",
    border: "none",
    borderTop: `1px solid rgba(255,255,255,0.12)`,
    borderRadius: side === "right" ? "0 10px 10px 0" : "10px 0 0 10px",
    filter: "none",
    boxShadow: active
      ? `inset 0 1px 0 rgba(255,255,255,0.14), inset 0 -3px 8px rgba(0,0,0,0.45)`
      : `inset 0 -2px 6px rgba(0,0,0,0.40)`,
    transition: "box-shadow 0.12s, background-image 0.12s",
  }),
  stepTabLabel: (active, ready) => ({
    fontSize: 17, color: active ? PARCHMENT : ready ? "rgba(242,232,208,0.90)" : "rgba(242,232,208,0.50)",
    letterSpacing: 0.2, lineHeight: 0.9, whiteSpace: "nowrap",
    writingMode: "vertical-rl", textOrientation: "mixed", transform: "rotate(180deg)",
    fontStyle: "italic", fontWeight: active ? 700 : 400,
    textShadow: "0 1px 3px rgba(0,0,0,0.65)",
  }),
  readyDot: { width: 3.5, height: 3.5, borderRadius: "50%", background: GOLD, position: "absolute", top: 1.5, right: 1.5, boxShadow: "0 0 4px rgba(201,168,76,0.9)" },
  pages: { flex: 1, minWidth: 0, display: "flex", position: "relative", backgroundImage: "linear-gradient(rgba(18,10,3,0.55), rgba(12,7,2,0.60)), url('/textures/parchment-warm.jpg')", backgroundSize: "cover", backgroundPosition: "center" },
  page: { flex: 1, minWidth: 0, overflowY: "auto", padding: "36px 30px 60px", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center" },
  fullPage: { flex: 1, minWidth: 0, overflowY: "auto", padding: "40px 56px 70px", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center" },
  fullPageInner: { maxWidth: 880, margin: "0 auto", textAlign: "left" },
  spreadEyebrowBig: { fontFamily: "'Georgia',serif", fontSize: 22, letterSpacing: 4, color: "rgba(55,28,8,0.85)", textTransform: "uppercase", marginBottom: 14, fontWeight: 700 },
  classGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(230px, 1fr))", gap: 14 },
  classCard: (color) => ({
    background: "transparent", borderTop: `3px solid ${color}`, borderRight: `1px solid rgba(139,90,20,0.22)`, borderBottom: `1px solid rgba(139,90,20,0.22)`, borderLeft: `1px solid rgba(139,90,20,0.22)`,
    borderRadius: 3, padding: "16px 17px", cursor: "pointer", transition: "background 0.15s",
  }),
  classCardEyebrow: () => ({ fontSize: 8.5, letterSpacing: 2.5, color: "rgba(100,68,18,0.78)", marginBottom: 6, textTransform: "uppercase" }),
  classCardTitle: { fontSize: 16.5, fontWeight: 700, color: "rgba(22,8,2,0.90)", marginBottom: 7, lineHeight: 1.2 },
  classCardBlurb: { fontSize: 12.5, lineHeight: 1.55, color: "rgba(22,8,2,0.70)", marginBottom: 10 },
  classCardMeta: { fontSize: 9.5, letterSpacing: 1, color: "rgba(100,68,18,0.58)" },
  backLink: { fontSize: 12, letterSpacing: 2, color: "rgba(55,28,8,0.85)", cursor: "pointer", marginBottom: 22, display: "inline-flex", alignItems: "center", gap: 8, background: "rgba(201,168,76,0.08)", border: "1px solid rgba(139,90,20,0.35)", borderRadius: 20, padding: "6px 16px 6px 12px" },
  divEyebrow: () => ({ fontSize: 10, letterSpacing: 5, color: "rgba(55,28,8,0.72)", textTransform: "uppercase", marginBottom: 12, display: "flex", alignItems: "center", gap: 10 }),
  divH1: { fontFamily: "'Georgia',serif", fontSize: "clamp(32px,4.5vw,50px)", fontWeight: 900, color: "rgba(22,8,2,0.92)", letterSpacing: -0.5, lineHeight: 1, marginBottom: 10 },
  divRange: { fontSize: 13, color: "rgba(55,28,8,0.68)", letterSpacing: 1.5, marginBottom: 16 },
  divTagline: { fontStyle: "italic", fontSize: 17, color: "rgba(22,8,2,0.80)", lineHeight: 1.6, maxWidth: 680, marginBottom: 30 },
  sectionLabel: () => ({ fontSize: 10, letterSpacing: 3.5, color: "rgba(100,68,18,0.80)", textTransform: "uppercase", marginBottom: 14, paddingBottom: 8, borderBottom: `1px solid rgba(139,90,20,0.25)` }),
  prose: { fontSize: 15.5, lineHeight: 1.8, color: "rgba(22,8,2,0.85)", marginBottom: 30 },
  bookGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px,1fr))", gap: 13, marginBottom: 8 },
  bookCard: (color) => ({
    background: "transparent", borderTop: `1px solid rgba(139,90,20,0.18)`, borderRight: `1px solid rgba(139,90,20,0.18)`, borderBottom: `1px solid rgba(139,90,20,0.18)`, borderLeft: `3px solid ${color}`,
    borderRadius: 3, padding: "13px 15px", cursor: "pointer", transition: "background 0.15s",
  }),
  bookCardTitle: { fontSize: 14.5, fontWeight: 700, color: "rgba(22,8,2,0.90)", marginBottom: 5, display: "flex", alignItems: "center", gap: 8, justifyContent: "space-between" },
  bookCardReason: { fontSize: 12.5, lineHeight: 1.55, color: "rgba(22,8,2,0.68)" },
  bookCardBadge: { fontSize: 8, letterSpacing: 1.5, color: "rgba(100,68,18,0.88)", border: `1px solid rgba(139,90,20,0.40)`, padding: "2px 6px", borderRadius: 2, flexShrink: 0 },
  calloutGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginBottom: 30 },
  callout: { background: "transparent", border: `1px solid rgba(139,90,20,0.22)`, borderRadius: 3, padding: "16px 18px" },
  calloutLabel: { fontSize: 9, letterSpacing: 3, color: "rgba(100,68,18,0.78)", marginBottom: 8, textTransform: "uppercase" },
  calloutText: { fontSize: 14, lineHeight: 1.7, color: "rgba(22,8,2,0.82)" },
  sienna: { background: "rgba(139,58,42,0.05)", borderLeft: `3px solid rgba(139,58,42,0.65)`, padding: "15px 18px", borderRadius: "0 3px 3px 0", marginBottom: 30 },
  siennaLabel: { fontSize: 9, letterSpacing: 3, color: "rgba(100,35,15,0.90)", marginBottom: 8, textTransform: "uppercase", fontWeight: 700 },
  siennaText: { fontSize: 14, lineHeight: 1.75, color: "rgba(22,8,2,0.82)", fontStyle: "italic" },
  verseBox: { background: "rgba(201,168,76,0.06)", border: `1px solid rgba(139,90,20,0.25)`, borderRadius: 3, padding: "18px 22px", marginBottom: 32, textAlign: "center" },
  verseRef: { fontSize: 11, letterSpacing: 3, color: "rgba(100,68,18,0.82)", marginBottom: 8, fontWeight: 700 },
  comingSoon: { textAlign: "center", padding: "50px 20px", border: `1px dashed rgba(201,168,76,0.25)`, borderRadius: 4, color: "rgba(242,232,208,0.5)" },
  comingSoonTitle: { fontSize: 17, color: PARCHMENT, marginBottom: 8, fontStyle: "italic" },
  mobileNote: { fontSize: 11, color: "rgba(242,232,208,0.4)", textAlign: "center", marginTop: 14, letterSpacing: 0.5 },
};

// ── BOOK VIEWER STYLES (GS) ───────────────────────────────────────────────────
export const GS = {
  app: { fontFamily: "'Georgia', serif", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center", backgroundAttachment: "local", color: PARCHMENT, minHeight: "100vh", overflowX: "hidden" },
  topBar: { height: 3, background: `linear-gradient(90deg, transparent, ${GOLD}, ${SIENNA}, ${GOLD}, transparent)` },
  header: { textAlign: "center", padding: "48px 20px 32px", borderBottom: `1px solid rgba(201,168,76,0.3)`, backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center top" },
  eyebrow: { fontFamily: "'Georgia',serif", fontSize: 10, letterSpacing: 6, color: "rgba(90,50,15,0.8)", textTransform: "uppercase", marginBottom: 14, opacity: 1 },
  h1: { fontFamily: "'Georgia',serif", fontSize: "clamp(44px,7vw,88px)", fontWeight: 900, color: "rgba(18,8,2,0.92)", letterSpacing: -1, lineHeight: 0.92, marginBottom: 6 },
  hebrew: { fontSize: "clamp(20px,3.5vw,36px)", color: "rgba(130,75,20,0.80)", letterSpacing: 8, marginBottom: 12, direction: "rtl" },
  subline: { fontStyle: "italic", fontSize: 17, color: "rgba(55,28,8,0.82)", maxWidth: 480, margin: "0 auto 20px", lineHeight: 1.6 },
  badgeRow: { display: "flex", justifyContent: "center", gap: 12, flexWrap: "wrap" },
  badge: { fontFamily: "'Georgia',serif", fontSize: 10, letterSpacing: 3, color: GOLD, border: `1px solid rgba(201,168,76,0.4)`, padding: "5px 12px", borderRadius: 2 },
  eraLegend: { display: "flex", justifyContent: "center", gap: 16, flexWrap: "wrap", padding: "12px 20px", background: "rgba(201,168,76,0.08)", borderBottom: `1px solid rgba(139,90,20,0.18)` },
  eraDot: { display: "flex", alignItems: "center", gap: 8, fontSize: 11, color: "rgba(50,25,6,0.82)" },
  infoPanel: { backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center", borderBottom: `1px solid rgba(201,168,76,0.2)` },
  tabNavWrap: { position: "relative" },
  tabNav: { display: "flex", borderBottom: `1px solid rgba(139,90,20,0.30)`, overflowX: "auto", padding: "0 0", gap: 0, scrollbarWidth: "none", msOverflowStyle: "none", backgroundImage: "linear-gradient(rgba(210,170,90,0.28), rgba(185,140,55,0.20)), url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center", borderTop: `1px solid rgba(139,90,20,0.20)` },
  tabNavFade: { position: "absolute", right: 0, top: 0, bottom: 1, width: 80, background: `linear-gradient(90deg, transparent, rgba(210,180,120,0.95))`, pointerEvents: "none", display: "flex", alignItems: "center", justifyContent: "flex-end", paddingRight: 10 },
  tabBtn: (active) => ({
    fontFamily: "'Georgia',serif", fontSize: 14, fontWeight: 600, letterSpacing: 1.5,
    color: active ? "rgba(60,30,5,1)" : "rgba(80,50,12,0.65)",
    background: active ? "rgba(201,168,76,0.30)" : "transparent",
    border: "none", borderBottom: active ? `2px solid rgba(139,90,20,1)` : "2px solid transparent",
    borderRadius: "10px 10px 0 0",
    padding: "16px 20px 14px", cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0,
    transition: "color 0.2s, border-color 0.2s, background 0.2s",
  }),
  tabPanels: { padding: "28px 32px 32px", textAlign: "left" },
  metaGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px,1fr))", gap: 20, marginBottom: 24 },
  metaBlock: { borderLeft: `2px solid rgba(139,90,20,0.30)`, paddingLeft: 14 },
  metaLabel: { fontSize: 11, letterSpacing: 2.5, color: "rgba(100,68,18,0.80)", marginBottom: 6, textTransform: "uppercase", fontWeight: 600 },
  metaValue: { fontSize: 16, color: "rgba(22,8,2,0.90)", lineHeight: 1.45, fontWeight: 400 },
  divider: { height: 1, background: "linear-gradient(90deg,rgba(139,90,20,0.25),transparent)", margin: "18px 0" },
  prose: { fontSize: 17, lineHeight: 1.80, color: "rgba(22,8,2,0.88)", maxWidth: 1080 },
  theoGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))", gap: 16, marginBottom: 20 },
  theoCard: { background: "rgba(201,168,76,0.06)", border: `1px solid rgba(139,90,20,0.2)`, borderRadius: 3, padding: 18 },
  theoCardTitle: { fontSize: 11, letterSpacing: 2.5, color: "rgba(100,68,18,0.80)", fontWeight: 600, marginBottom: 10, paddingBottom: 8, borderBottom: `1px solid rgba(139,90,20,0.15)` },
  theoCardText: { fontSize: 15, lineHeight: 1.72, color: "rgba(22,8,2,0.85)" },
  tagsRow: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 16 },
  tag: { fontSize: 10, letterSpacing: 1.5, background: "rgba(201,168,76,0.08)", border: `1px solid rgba(201,168,76,0.25)`, color: "rgba(118,84,22,0.85)", padding: "4px 10px", borderRadius: 2 },
  wcfItem: { display: "flex", gap: 10, padding: "10px 0", borderBottom: `1px solid rgba(139,90,20,0.1)`, fontSize: 15, color: "rgba(22,8,2,0.85)", lineHeight: 1.55 },
  purposeCols: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 },
  purposeColTitle: { fontSize: 11, letterSpacing: 2.5, fontWeight: 600, color: "rgba(100,68,18,0.82)", marginBottom: 12, paddingBottom: 6, borderBottom: `1px solid rgba(139,90,20,0.2)` },
  audienceBox: { marginTop: 22, background: "linear-gradient(90deg,rgba(201,168,76,0.10),rgba(201,168,76,0.03))", borderLeft: `3px solid rgba(139,90,20,0.45)`, padding: "14px 18px", borderRadius: "0 3px 3px 0" },
  epochRow: { display: "flex", overflowX: "auto", marginBottom: 24, gap: 0 },
  epoch: (highlight) => ({
    flex: 1, minWidth: 130, padding: "16px 14px",
    borderTop: `${highlight ? "3px" : "1px"} solid ${highlight ? "rgba(155,108,26,0.80)" : "rgba(139,90,20,0.22)"}`,
    borderBottom: `1px solid rgba(139,90,20,0.15)`,
    borderLeft: `1px solid rgba(139,90,20,0.15)`,
    borderRight: "none",
    background: highlight ? "rgba(201,168,76,0.16)" : "rgba(139,90,20,0.04)",
  }),
  epochLast: { borderRight: `1px solid rgba(139,90,20,0.15)` },
  epochLabel: (highlight) => ({ fontSize: 10, letterSpacing: 1.5, fontWeight: 600, color: highlight ? "rgba(100,68,18,0.92)" : "rgba(80,55,15,0.60)", marginBottom: 5 }),
  epochTitle: (highlight) => ({ fontSize: highlight ? 17 : 15, fontWeight: highlight ? 800 : 500, color: highlight ? "rgba(15,5,1,0.95)" : "rgba(28,12,3,0.60)", lineHeight: 1.25, marginBottom: 6 }),
  epochBooks: (highlight) => ({ fontSize: 12, color: highlight ? "rgba(45,28,8,0.82)" : "rgba(45,28,8,0.45)", letterSpacing: 0.5, lineHeight: 1.5 }),
  christBox: { background: "rgba(201,168,76,0.07)", border: `1px solid rgba(139,90,20,0.22)`, borderRadius: 3, padding: "18px 22px", marginBottom: 18 },
  typesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(250px,1fr))", gap: 10 },
  typeItem: { display: "flex", gap: 10, padding: "11px 13px", background: "rgba(201,168,76,0.06)", border: `1px solid rgba(139,90,20,0.15)`, borderRadius: 3, fontSize: 14, color: "rgba(22,8,2,0.85)", lineHeight: 1.55 },
  verseEntry: { display: "flex", gap: 18, padding: "18px 0", borderBottom: `1px solid rgba(139,90,20,0.12)`, alignItems: "flex-start" },
  verseRef: { fontWeight: 700, fontSize: 14, color: "#1E4A7A", minWidth: 85, paddingTop: 3, letterSpacing: 0.5, flexShrink: 0 },
  verseText: { fontStyle: "italic", fontSize: 18, color: "rgba(22,8,2,0.88)", lineHeight: 1.65, marginBottom: 6 },
  verseNote: { fontSize: 14, color: "rgba(55,32,8,0.72)", lineHeight: 1.55 },
  sourcesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: 12 },
  sourceCard: { background: "rgba(201,168,76,0.06)", border: `1px solid rgba(139,90,20,0.28)`, borderRadius: 3, padding: "16px 18px" },
  sourceTier: { fontSize: 11, letterSpacing: 2.5, fontWeight: 700, color: "rgba(80,45,10,0.92)", marginBottom: 6 },
  sourceTitle: { fontSize: 17, fontWeight: 700, color: "rgba(22,8,2,0.92)", lineHeight: 1.3, marginBottom: 4 },
  sourceAuthor: { fontStyle: "italic", fontSize: 14, color: "rgba(35,15,4,0.80)", marginBottom: 4 },
  sourceMeta: { fontSize: 12, letterSpacing: 1.5, color: "rgba(80,50,12,0.82)" },
  timelineWrap: { overflowX: "auto", padding: "18px 40px 100px", cursor: "grab", position: "relative", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center" },
  timelineInner: { position: "relative", width: 4200, height: 520 },
  spine: { position: "absolute", top: "50%", left: 0, right: 0, height: 2, background: `linear-gradient(90deg,transparent,rgba(201,168,76,0.3) 2%,${GOLD} 20%,${GOLD} 80%,rgba(201,168,76,0.3) 98%,transparent)`, transform: "translateY(-50%)" },
  overlay: (open) => ({ position: "fixed", inset: 0, background: "rgba(18,10,3,0.65)", backdropFilter: "blur(4px)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: "max(16px, env(safe-area-inset-top,16px)) 16px max(16px, env(safe-area-inset-bottom,16px))", opacity: open ? 1 : 0, pointerEvents: open ? "all" : "none", transition: "opacity 0.25s" }),
  popupCard: { background: "#EFE0BC", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center", border: `1px solid rgba(139,90,20,0.40)`, borderRadius: 12, width: "100%", maxWidth: 680, maxHeight: "82dvh", overflowY: "auto", overscrollBehavior: "contain", position: "relative", boxShadow: "0 8px 40px rgba(40,18,4,0.30)", textAlign: "left", animation: "sheetUp 0.8s cubic-bezier(0.22,1,0.36,1) both" },
  popupHeader: { padding: "28px 28px 20px", borderBottom: `1px solid rgba(139,90,20,0.18)`, display: "flex", gap: 20, alignItems: "flex-start" },
  popupAvatar: (color) => ({ width: 96, height: 96, borderRadius: 12, border: `2px solid ${color}`, background: `rgba(235,218,185,0.85)`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 28, fontWeight: 700, color, flexShrink: 0 }),
  popupBadge: (color) => ({ display: "inline-block", fontSize: 9, letterSpacing: 3, color, border: `1px solid rgba(139,90,20,0.35)`, padding: "3px 9px", marginBottom: 7, borderRadius: 2 }),
  popupName: { fontSize: 26, fontWeight: 700, color: "rgba(22,8,2,0.92)", lineHeight: 1.1, marginBottom: 5 },
  popupChapters: (color) => ({ fontSize: 12, color, letterSpacing: 1, marginBottom: 10 }),
  popupDesc: { fontStyle: "italic", fontSize: 15, color: "rgba(22,8,2,0.78)", lineHeight: 1.65 },
  popupBody: { padding: "20px 28px 28px" },
  popupSectionTitle: { fontSize: 9, letterSpacing: 4, color: "rgba(100,68,18,0.85)", marginBottom: 9, paddingBottom: 5, borderBottom: `1px solid rgba(139,90,20,0.20)`, marginTop: 18 },
  popupText: { fontSize: 15, lineHeight: 1.7, color: "rgba(22,8,2,0.82)" },
  typeBanner: { background: "rgba(139,90,20,0.07)", borderLeft: `3px solid rgba(139,90,20,0.55)`, padding: "11px 14px", borderRadius: "0 3px 3px 0", marginTop: 8 },
  ntBox: { background: "rgba(201,168,76,0.07)", border: `1px solid rgba(139,90,20,0.22)`, borderRadius: 3, padding: "11px 14px", marginTop: 8, fontSize: 14, lineHeight: 1.65, color: "rgba(22,8,2,0.82)" },
  closeBtn: { position: "absolute", top: 14, right: 14, width: 30, height: 30, background: "rgba(139,90,20,0.10)", border: `1px solid rgba(139,90,20,0.30)`, borderRadius: "50%", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: "rgba(55,28,8,0.80)", fontSize: 15, zIndex: 10 },
  versChips: { display: "flex", flexWrap: "wrap", gap: 7, marginTop: 8 },
  versChip: { fontSize: 11, letterSpacing: 0.5, fontWeight: 600, background: "rgba(30,74,122,0.08)", border: `1px solid rgba(30,74,122,0.40)`, color: "#1E4A7A", padding: "4px 10px", borderRadius: 2 },
  chTooltip: { position: "fixed", background: "#EFE0BC", backgroundImage: "url('/textures/pergament.jpg')", backgroundSize: "cover", backgroundPosition: "center", border: `1px solid rgba(139,90,20,0.35)`, borderRadius: 10, padding: "16px 18px", maxWidth: 280, pointerEvents: "none", zIndex: 500, boxShadow: "0 6px 24px rgba(40,18,4,0.22)", textAlign: "left" },
  chTooltipCh: { fontSize: 9, letterSpacing: 3, color: "rgba(100,68,18,0.80)", marginBottom: 3 },
  chTooltipTitle: { fontSize: 16, fontWeight: 700, color: "rgba(22,8,2,0.92)", marginBottom: 7, lineHeight: 1.2 },
  chTooltipDesc: { fontSize: 13, lineHeight: 1.6, color: "rgba(22,8,2,0.72)", marginBottom: 8 },
  chTooltipVerse: { fontSize: 9, letterSpacing: 2, color: "rgba(100,68,18,0.65)" },
};
